version: "3.8"

services:
  # Tempo - Distributed tracing backend
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ${PWD}/observability/tempo/tempo.yaml:/etc/tempo.yaml
      # - tempo_data:/data/tempo/
    ports:
      - "3200:3200" # Tempo
      - "4318:4318" # OTLP HTTP Receiver
      - "4317:4317" # OTLP gRPC Receiver
    networks:
      - observability

  # Prometheus - Metrics collection and storage
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${PWD}/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks:
      - observability
    depends_on:
      - tempo

  # Loki - Log aggregation system
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ${PWD}/observability/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - observability

  # Grafana - Visualization platform
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ${PWD}/observability/grafana/datasources:/etc/grafana/provisioning/datasources
      - ${PWD}/observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3300:3000"
    networks:
      - observability
    depends_on:
      - prometheus
      - loki
      - tempo

networks:
  observability:
    driver: bridge

volumes:
  tempo_data:
  prometheus_data:
  loki_data:
  grafana_data:
