global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add a job for the Area51 Phoenix application (if it exposes metrics)
  # Job name needs to match with PromEx module
  - job_name: 'area51_web'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:4000']

remote_write:
  - url: http://tempo:3200/api/v1/traces
    remote_timeout: 30s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'traces_.+'
        action: keep
