global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

remote_write:
  - url: http://tempo:3200/api/v1/traces
    remote_timeout: 30s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'traces_.+'
        action: keep
